/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lemmsh' at '7/26/15 4:07 PM' with Gradle 2.5
 *
 * @author lemmsh, @date 7/26/15 4:07 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
